version: '3.3'
services:
   jenkins: 
        image: jenkins
        container_name: jenkins
        restart: always
        ports:
          - 8080:8080
        volumes:
          - ./jenkins01:/var/jenkins_home --name jenkins jenkins     
